name: slimfire

channels:
  - conda-forge

dependencies:
  - python=3.12
  - fastapi
  - geopandas
  - pandas
  - pyogrio
  - python-dotenv
  - requests
  - rio-tiler
  - scikit-learn
  - scipy
  - uvicorn
  - pillow
  - rasterio
  - pip
  - pip:
      - nfdrs4py==0.2.2
      - openeo
